# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - refs/heads/master
  paths:
    include:
    - deploy.ps1
    - build.ps1
    - M365Configuration.ps1

variables:
  buildFolderName: output
  buildArtifactName: deploypackage

pool: Microsoft365Dsc

steps:
- task: AzureKeyVault@1
  displayName: 'Azure Key Vault: M365DscKeyVault'
  inputs:
    azureSubscription: KeyVaultConnection
    KeyVaultName: M365DscKeyVault
    SecretsFilter: 'DscConfigAdmin'

- task: PowerShell@2
  displayName: 'Run Build script'
  inputs:
    targetType: 'filePath'
    filePath: 'build.ps1'
    pwsh: false
    failOnStderr: true
    errorActionPreference: 'stop'
  env:
    SAPW: $(DscConfigAdmin)

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifacts'
  inputs:
    targetPath: '$(buildFolderName)/'
    artifact: $(buildArtifactName)
    publishLocation: 'pipeline'
    parallel: true
